webtalk_init -webtalk_dir C:/Users/nmari/Documents/GitHub/mphei_riscv_mcu_22/hard/src/common/top/work/def_prj/def_prj.sim/sim_1/behav/xsim/xsim.dir/tb_mpei_rv_core_wrp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 22 11:06:37 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d77e3f42-13a9-4d53-a160-28cd0972a4f3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bef623e15a144978bbb22d3ccd2017e8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "82" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "761 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "653 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1464" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "83" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "47.50_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "275536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 469846262 -regid "" -xml C:/Users/nmari/Documents/GitHub/mphei_riscv_mcu_22/hard/src/common/top/work/def_prj/def_prj.sim/sim_1/behav/xsim/xsim.dir/tb_mpei_rv_core_wrp_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/nmari/Documents/GitHub/mphei_riscv_mcu_22/hard/src/common/top/work/def_prj/def_prj.sim/sim_1/behav/xsim/xsim.dir/tb_mpei_rv_core_wrp_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/nmari/Documents/GitHub/mphei_riscv_mcu_22/hard/src/common/top/work/def_prj/def_prj.sim/sim_1/behav/xsim/xsim.dir/tb_mpei_rv_core_wrp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
