@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jul 22 11:05:49 +0300 2022
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto bef623e15a144978bbb22d3ccd2017e8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L grlib -L gaisler -L work -L techmap -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mpei_rv_core_wrp_behav xil_defaultlib.tb_mpei_rv_core_wrp xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto bef623e15a144978bbb22d3ccd2017e8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L grlib -L gaisler -L work -L techmap -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_mpei_rv_core_wrp_behav xil_defaultlib.tb_mpei_rv_core_wrp xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
